# Generated by Django 5.0.6 on 2024-06-29 09:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('cow_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('cow_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('eye_color', models.CharField(blank=True, max_length=50, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationDoctor',
            fields=[
                ('doctor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=100)),
                ('doctor_nat_id', models.FloatField()),
                ('doctor_email', models.EmailField(max_length=100)),
                ('doctor_phone', models.CharField(max_length=15)),
                ('treated_cow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cow.cow')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('vaccination_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vaccination_type', models.CharField(max_length=100)),
                ('vaccination_date', models.DateField()),
                ('cow_vaccinated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='cow.cow')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='cow.vaccinationdoctor')),
            ],
        ),
    ]
