# Generated by Django 5.0.6 on 2024-06-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='gender',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
