# Generated by Django 5.0.6 on 2024-06-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0002_cow_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cow',
            name='cow_weight',
        ),
        migrations.AddField(
            model_name='cow',
            name='status',
            field=models.CharField(default='available', max_length=50),
        ),
    ]
