# Generated by Django 5.0.6 on 2024-07-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0003_remove_cow_cow_weight_cow_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationdoctor',
            name='doctor_phone',
            field=models.IntegerField(max_length=15),
        ),
    ]
