# Generated by Django 5.0.6 on 2024-07-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0004_alter_vaccinationdoctor_doctor_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationdoctor',
            name='doctor_phone',
            field=models.IntegerField(),
        ),
    ]
