# Generated by Django 5.0.6 on 2024-06-29 09:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cow', '0001_initial'),
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('milk_produced', models.FloatField()),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cow.cow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='FeedingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feed_date', models.DateField()),
                ('feed_type', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('production_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairy.productionrecord')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionRecordHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('milk_produced', models.FloatField()),
                ('action', models.CharField(default='Updated', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cow.cow')),
                ('production_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairy.productionrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
