# Generated by Django 5.0.6 on 2024-07-01 19:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0005_alter_vaccinationdoctor_doctor_phone'),
        ('dairy', '0001_initial'),
        ('users', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sale_date', models.DateField()),
                ('milk_sold', models.FloatField()),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cow.cow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
