# Generated by Django 5.0.6 on 2024-07-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0002_salesrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrecord',
            name='price_per_liter',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
