# Generated by Django 5.0.6 on 2024-07-03 10:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0005_alter_vaccinationdoctor_doctor_phone'),
        ('dairy', '0003_productionrecord_price_per_liter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedingrecord',
            name='cow',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cow.cow'),
        ),
        migrations.AddField(
            model_name='feedingrecord',
            name='feed_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='feedingrecord',
            name='supplements',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
