# Generated by Django 5.0.6 on 2024-07-04 09:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0004_feedingrecord_cow_feedingrecord_feed_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedingrecord',
            name='production_record',
        ),
        migrations.AlterField(
            model_name='feedingrecord',
            name='feed_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
