# Generated by Django 5.0.6 on 2024-07-04 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0005_remove_feedingrecord_production_record_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionrecord',
            name='price_per_liter',
        ),
        migrations.RemoveField(
            model_name='productionrecord',
            name='total',
        ),
    ]
