# Generated by Django 5.0.6 on 2024-07-04 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0006_remove_productionrecord_price_per_liter_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesRecord',
        ),
    ]
