# Generated by Django 5.0.6 on 2024-07-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='user',
            name='natid',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
