# Generated by Django 5.0.6 on 2024-07-04 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_is_staff_user_natid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailaddress',
            old_name='email',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='username',
        ),
    ]
