# Generated by Django 5.0.6 on 2024-07-05 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_email_emailaddress_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_emailaddress_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
