# Generated by Django 5.0.6 on 2024-07-05 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_emailaddress_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailAddress',
        ),
    ]
