# Generated by Django 5.0.6 on 2024-07-04 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dairy', '0007_delete_salesrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('price_per_ltr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField()),
                ('liter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairy.productionrecord')),
                ('milk_collection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_as_milk_collection', to='dairy.productionrecord')),
            ],
        ),
    ]
