# Generated by Django 5.0.6 on 2024-07-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='liter',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
